language: node_js

node_js:
  - 7

sudo: required
services: 
  - docker

before_install:
  - docker build -f Dockerfile.dev -t surajdockerdemo/docker-node .

script:
  - docker run surajdockerdemo/docker-node